#vebragax
language: node_js
node_js:
  - 10.9.0

cache: npm

install:
  - npm install

script:
  - npm run build
  - npm run test

before_install:
  - "npm config set spin false"
  - npm i -g now

<<<<<<< HEAD
=======
install:
  - npm install
  
 env:
  - DB=postgres
  - SH=bash
  - PACKAGE_VERSION="1.0.*"

>>>>>>> 396dab28158c42432cbae8c5525ec385561d817d
deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true
