#vebragax
language: node_js
node_js:
  - 10.9.0

cache: npm

env:
  - NOW_TOKEN=QWDH0Kwi9774ZkJtKhx8Oqis

install:
  - npm install

script:
  - npm run build
  - npm run test

before_install:
  - mkdir public
  - "npm config set spin false"
  - npm i -g now

deploy:
  provider: script
  script: bash ./scripts/deploy.sh
  skip_cleanup: true
